[package]
name = "rlk"
version = "0.1.0"
authors = ["Adrian Danis <rambobones@gmail.com>"]
license = "MIT"
readme = "README.md"
publish = false

[build-dependencies]
cc = "1.0"

[dependencies]
rlibc = "1.0.0"

[profile.release]
lto = true
